### ISSUE TITLE
The script not working anymore. 

### ISSUE THREAD

**Issue by kexul** [camenduru/SMPLer-X-hf#1]
Would you mind fix it?

ImportError: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

**Comment by camenduru** [comment]
please use: https://github.com/caizhongang/SMPLer-X
